handling error smoothly during stop loading
e.g. error caused by deleted BasicSignal of AsyncFun
AttributeError: 'BasicSignal' does not have a signal with the signature finished()